version: "3"

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24

services:

  wg_dashboard:
    image: noxcis/wg-dashboard:latest
    container_name: wg_dashboard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
    volumes:
      - ./WG-Dash/config:/etc/wireguard
    environment:
      - SERVER_IP=127.0.0.1
      - CONFIG_CT=1
    ports:
      - 10086:10086
      - 51820:51820/udp
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      private_network:
        ipv4_address: 10.2.0.3
