
version: "3"

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24

services:
  unbound:
    image: "klutchell/unbound:latest"
    container_name: unbound
    restart: unless-stopped
    hostname: "unbound"
    volumes:
      - ./Global-Configs/Unbound/custom-unbound.conf:/etc/unbound/custom.conf.d/custom-unbound.conf
    networks:
      private_network:
        ipv4_address: 10.2.0.200

  adguard:
    depends_on: [unbound]
    container_name: adguard
    image: adguard/adguardhome
    restart: unless-stopped
    hostname: adguard
    # Volumes store your data between container upgrades
    volumes:
      - "./adguard/opt-adguard-work:/opt/adguardhome/work"
      - "./adguard/opt-adguard-conf:/opt/adguardhome/conf"
    networks:
      private_network:
        ipv4_address: 10.2.0.100


  wg_dashboard:
    depends_on: [unbound, adguard]
    #build: ./Apps/WG-Dash
    image: noxcis/wg-dashboard:orca
    container_name: wg_dashboard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
    volumes:
      - ./Apps/WG-Dash/master-key:/home/app/master-key
    environment:
      - WG_DASH_USER=admin
      - WG_DASH_PASS_ENCRYPTED="$$2a$$12$$DqKBORUB7.3sBiUXNQ8Fg.mX861V0jI3qwVGAAjNt9UCBjdMRLHeW"
      - WGDASH_SECRET_KEY=nidfsnnsknfkscsnksjnjc
      - SERVER_IP=0.0.0.0
      - CONFIG_CT=6000
      - START_PORT=770
    ports:
      - "770-777:770-777/udp"
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      private_network:
        ipv4_address: 10.2.0.3

  
  darkwire:
    container_name: darkwire
    build: ./Apps/Darkwire
    environment:
      - TZ=UTC
      - VITE_API_PORT=80
      - VITE_API_HOST=localhost
      - VITE_API_PROTOCOL=http
      - VITE_COMMIT_SHA=some_sha
      - VITE_MAX_FILE_SIZE=4
      - MAILGUN_API_KEY=api-key
      - MAILGUN_DOMAIN=darkwire.io
      - ABUSE_TO_EMAIL_ADDRESS=abuse@darkwire.io
      - ABUSE_FROM_EMAIL_ADDRESS=Darkwire <no-reply@darkwire.io>
      - CLIENT_DIST_DIRECTORY='client/dist'
      - ROOM_HASH_SECRET='some-uuid'
      - SITE_URL=https://darkwire.io
      - STORE_BACKEND=memory
      #- STORE_HOST=$STORE_HOST
    #ports:
      #- 80:80
    networks:
      private_network:
        ipv4_address: 10.2.0.6
  

volumes:
    postgres_data:
  