
version: "3"

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24
     

services:
  unbound:
    image: "klutchell/unbound:latest"
    container_name: unbound
    restart: unless-stopped
    hostname: "unbound"
    volumes:
      - ./Global-Configs/Unbound/custom-unbound.conf:/etc/unbound/custom.conf.d/custom-unbound.conf
    networks:
      private_network:
        ipv4_address: 10.2.0.200

  adguard:
    depends_on: [unbound]
    container_name: adguard
    image: adguard/adguardhome
    restart: unless-stopped
    hostname: adguard
    # Volumes store your data between container upgrades
    volumes:
      - "./adguard/opt-adguard-work:/opt/adguardhome/work"
      - "./adguard/opt-adguard-conf:/opt/adguardhome/conf"
    networks:
      private_network:
        ipv4_address: 10.2.0.100


  wg_dashboard:
    depends_on: [unbound, adguard]
    build: ./WG-Dash
    #image: noxcis/wg-dashboard:cetus
    container_name: wg_dashboard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
    volumes:
      - ./Global-Configs/Wiregate-Database:/home/app/db
      - ./Global-Configs/Master-Key:/home/app/master-key
      - ./Global-Configs/Firewall-Rules:/home/app/FIREWALLS
    environment:
      - WG_DASH_USER=admin
      - WG_DASH_PASS=admin
      - WG_DASH_SECRET_KEY=some-super-secret_key
      - WG_DASH_SERVER_IP=0.0.0.0
      - WG_DASH_DNS=10.2.0.100, 10.2.0.100
      - WG_DASH_PEER_ENDPOINT_ALLOWED_IP=0.0.0.0/0
      - WG_DASH_KEEP_ALIVE=21
      - WG_DASH_MTU=1420
      - WG_DASH_PORT_RANGE_STARTPORT=770
    ports:
      - "770-772:770-772/udp"
      - 8080:80/tcp
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      private_network:
        ipv4_address: 10.2.0.3


  