version: "3"

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24

services:
  unbound:
    image: "klutchell/unbound:latest"
    container_name: unbound
    restart: unless-stopped
    hostname: "unbound"
    volumes:
      - ./Global-Configs/Unbound/custom-unbound.conf:/etc/unbound/custom.conf.d/custom-unbound.conf
    networks:
      private_network:
        ipv4_address: 10.2.0.200

  wg_dashboard:
    depends_on: [unbound, adguard]
    #build: ./WG-Dash
    image: noxcis/wg-dashboard:moray-multi-arch
    container_name: wg_dashboard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
    volumes:
      - ./WG-Dash/master-key:/home/app/master-key
    environment:
      - WG_DASH_USER=${WG_DASH_USER}
      - WG_DASH_PASS_ENCRYPTED=${WG_DASH_PASS_ENCRYPTED}
      - SERVER_IP=${SERVER_IP}
      - CONFIG_CT=${INTERFACE_COUNT}
      - START_PORT=${PORT_RANGE_START}
    ports:
      - "${PORT_MAPPINGS}"
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      private_network:
        ipv4_address: 10.2.0.3



  adguard:
    depends_on: [unbound]
    container_name: adguard
    image: adguard/adguardhome
    restart: unless-stopped
    hostname: adguard
    # Volumes store your data between container upgrades
    volumes:
      - "./adguard/opt-adguard-work:/opt/adguardhome/work"
      - "./adguard/opt-adguard-conf:/opt/adguardhome/conf"
    networks:
      private_network:
        ipv4_address: 10.2.0.100


  channels:
    depends_on: [db, wg_dashboard]
    container_name: channels_messenger
    #build: ./Channels
    image: noxcis/channels:moray-multi-arch
    restart: unless-stopped
    command: python run.py
    env_file:
      - ./Global-Configs/ENV-FILES/channels.env.dev
    networks:
      private_network:
        ipv4_address: 10.2.0.4


  db:
    container_name: channels_db
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./Global-Configs/ENV-FILES/channels_db.env.dev
    networks:
      private_network:
        ipv4_address: 10.2.0.5

volumes:
    postgres_data: