version: "3"

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24

services:
  unbound:
    image: "klutchell/unbound:latest"
    container_name: unbound
    restart: unless-stopped
    hostname: "unbound"
    volumes:
      - ./Global-Configs/Unbound/custom-unbound.conf:/etc/unbound/custom.conf.d/custom-unbound.conf
    networks:
      private_network:
        ipv4_address: 10.2.0.200

  adguard:
    depends_on: [unbound]
    container_name: adguard
    image: adguard/adguardhome
    restart: unless-stopped
    hostname: adguard
    # Volumes store your data between container upgrades
    volumes:
      - "./Global-Configs/AdGuard/Data:/opt/adguardhome/work"
      - "./Global-Configs/AdGuard/Config:/opt/adguardhome/conf"
    networks:
      private_network:
        ipv4_address: 10.2.0.100

  dockge:
    image: louislam/dockge:1
    container_name: dockge_gated
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Global-Configs/Dockge/data:/app/data
      - /opt/stacks:/opt/stacks
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks
    networks:
      private_network:
        ipv4_address: 10.2.0.2

  wg_dashboard:
    #build: ./WG-Dash
    image: noxcis/wg-dashboard:cetus
    container_name: wg_dashboard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
    volumes:
      - ./Global-Configs/Wiregate-Database:/home/app/db
      - ./Global-Configs/Master-Key:/home/app/master-key
      - ./Global-Configs/Firewall-Rules:/home/app/FIREWALLS
    env_file:
      - ./Global-Configs/WireGate-Deploy-ENV/wiregate.env
    ports:
      - "770-777:770-777/udp"
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      private_network:
        ipv4_address: 10.2.0.3

  channels:
    depends_on: [db, wg_dashboard]
    container_name: channels_messenger
    #build: ./Channels
    image: noxcis/channels:marlin
    restart: unless-stopped
    command: python run.py
    env_file:
      - ./Global-Configs/WireGate-Deploy-ENV/wiregate.env
    networks:
      private_network:
        ipv4_address: 10.2.0.4
    dns: 10.2.0.100

  db:
    container_name: channels_db
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./Global-Configs/WireGate-Deploy-ENV/wiregate.env
    networks:
      private_network:
        ipv4_address: 10.2.0.5
    dns: 10.2.0.100

volumes:
    postgres_data: