version: "3"

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24

    

services:
  unbound:
    image: "klutchell/unbound:latest"
    container_name: unbound
    restart: unless-stopped
    hostname: "unbound"
    volumes:
      - ./Global-Configs/Unbound/custom-unbound.conf:/etc/unbound/custom.conf.d/custom-unbound.conf
    networks:
      private_network:
        ipv4_address: 10.2.0.200

  wg_dashboard:
    depends_on: [unbound, adguard]
    build: ./WG-Dash
    #image: noxcis/wg-dashboard:marlin
    container_name: wg_dashboard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
    volumes:
      - ./WG-Dash/master-key:/home/app/master-key
    environment:
      - WG_DASH_USER=${WG_DASH_USER}
      - WG_DASH_PASS_ENCRYPTED=${WG_DASH_PASS_ENCRYPTED}
      - WGDASH_SECRET_KEY=${WGDASH_SECRET_KEY}
      - SERVER_IP=${SERVER_IP}
      - CONFIG_CT=3
      - START_PORT=770
    ports:
      - "770-772:770-772/udp"
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      private_network:
        ipv4_address: 10.2.0.3




  adguard:
    depends_on: [unbound]
    container_name: adguard
    image: adguard/adguardhome
    restart: unless-stopped
    hostname: adguard
    # Volumes store your data between container upgrades
    volumes:
      - "./adguard/opt-adguard-work:/opt/adguardhome/work"
      - "./adguard/opt-adguard-conf:/opt/adguardhome/conf"
    networks:
      private_network:
        ipv4_address: 10.2.0.100


 